In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [19]:
dataset=pd.read_csv('Book04.csv')
dataset.head()

   Unnamed: 0  input1  input2  input3      input4  input5  outcome
0           0     486       4      50  211.500000    8100   411156
1           1     394       8      99   34.600000    3025   109059
2           2     321       6      66   56.333333    6400   108498
3           3     419       8      92   63.000000    5476   211176
4           4     265       1       9   24.700000    4489     6546

In [20]:
X = dataset.iloc[:,[1,2,3,4,5]].values
y = dataset.iloc[:,6].values

In [21]:
from sklearn.cross_validation import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
y_test

array([ 135196,  215635,   56411,  126484,   25636,   22660,   70613,
        345118,   26448,    2626,  547470,   75015,   46991,   33905,
        359397,   83485,  698148,   86877,  417690,  120343,  144100,
        113524,   25260,    8137,  162250,  148471,   33200,  165222,
        107868,   27104,  161680,    2995,   62498,  108498,  310464,
        137172,  822213,   64023,  409920,   46632,   77868,  155364,
        303024,  109292,  411156,  649740,   40729,   39942,   78840,
         58319,   23400,   12971,  140567,  308430,    9472,   62424,
         65985,   14696, 1095930,   32448,  103415,   14364,  187438,
          6188,  152628,    7973,   25114,  219870,   75348,   16072,
         61126,  112979,   58560,   60300,  320839,   68586,  855050,
         18312,  161784,   36335,   13737,   63800,  188293,   44339,
         90297,   94523,   54855,   50218,  222705,  368060,   45687,
          8702, 1352160,  234675,  440000,   47840,   52275,  161838,
         22884,   11957], dtype=int64)

In [22]:
#scaling the values
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [23]:
from xgboost import XGBRegressor

In [24]:
regressor = XGBRegressor()  
regressor.fit(X_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, importance_type='gain',
       learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
       nthread=None, objective='reg:linear', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=True,
       subsample=1)

In [25]:
y_pred = regressor.predict(X_test)

In [26]:
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})  
df

     Actual     Predicted
0    135196  1.256727e+05
1    215635  1.979001e+05
2     56411  6.695521e+04
3    126484  1.186917e+05
4     25636  4.086105e+04
5     22660  2.090963e+04
6     70613  7.882627e+04
7    345118  1.871802e+05
8     26448  2.978823e+04
9      2626 -1.179030e+04
10   547470  5.489708e+05
11    75015  7.342811e+04
12    46991  5.094909e+04
13    33905  2.857044e+04
14   359397  3.938245e+05
15    83485  7.806432e+04
16   698148  7.687254e+05
17    86877  9.284091e+04
18   417690  3.837375e+05
19   120343  1.384299e+05
20   144100  3.165692e+05
21   113524  9.204119e+04
22    25260  2.726643e+04
23     8137  5.449954e+03
24   162250  1.115345e+05
25   148471  1.299097e+05
26    33200  3.642278e+04
27   165222  2.689734e+05
28   107868  9.933598e+04
29    27104  2.222777e+04
..      ...           ...
70    61126  6.014045e+04
71   112979  1.020951e+05
72    58560  5.996264e+04
73    60300  7.233455e+04
74   320839  2.946508e+05
75    68586  7.128318e+04
76   855050  7.393135e+05
77    18312  2.756574e+04
78   161784  1.492605e+05
79    36335  3.980803e+04
80    13737  4.434976e+03
81    63800  7.215286e+04
82   188293  2.029925e+05
83    44339  7.184361e+04
84    90297  1.050916e+05
85    94523  9.205631e+04
86    54855  5.105287e+04
87    50218  5.566520e+04
88   222705  2.168579e+05
89   368060  1.960949e+05
90    45687  3.822948e+04
91     8702  7.289375e+03
92  1352160  1.280568e+06
93   234675  1.109989e+05
94   440000  4.226396e+05
95    47840  7.076070e+04
96    52275  6.081050e+04
97   161838  3.475686e+05
98    22884  2.570750e+04
99    11957  1.129732e+04

[100 rows x 2 columns]

In [29]:
from sklearn import metrics
l=metrics.r2_score(y_pred, y_test)
l

0.9410853595248476

In [31]:
print('r2_score : {}'.format(l))
print('algorithm : XGBoostRegression')

r2_score : 0.9410853595248476
algorithm : XGBoostRegression